### PR TITLE
Add circleci

### PR DESCRIPTION
**Pull request by tfussell**
Just building and pushing the image. Not pushing to the app catalog as the helm chart is handled in https://github.com/giantswarm/cluster-api-provider-vsphere-app

### CODE REVIEW

**Comment by QuentinBisson** [comment]
@tfussell those only got reconciled once I added the watch filter label:

```json
I0325 12:45:43.274690       1 vspherecluster_controller.go:253] capv-controller-manager/vspherecluster-controller/quentin-reproduce/quentin-reproduce "msg"="Reconciling VSphereCluster"  
E0325 12:45:48.670697       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="unexpected error while probing vcenter for infrastructure.cluster.x-k8s.io/v1alpha3, Kind=VSphereCluster quentin-reproduce/quentin-reproduce: ServerFaultCode: Cannot complete login due to an incorrect user name or password." "controller"="vspherecluster" "name"="quentin-reproduce" "namespace"="quentin-reproduce"
I0325 12:45:48.676083       1 vspherecluster_controller.go:253] capv-controller-manager/vspherecluster-controller/quentin-reproduce/quentin-reproduce "msg"="Reconciling VSphereCluster"  
E0325 12:45:54.023619       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="unexpected error while probing vcenter for infrastructure.cluster.x-k8s.io/v1alpha3, Kind=VSphereCluster quentin-reproduce/quentin-reproduce: ServerFaultCode: Cannot complete login due to an incorrect user name or password." "controller"="vspherecluster" "name"="quentin-reproduce" "namespace"="quentin-reproduce"
I0325 12:45:54.033986       1 vspherecluster_controller.go:253] capv-controller-manager/vspherecluster-controller/quentin-reproduce/quentin-reproduce "msg"="Reconciling VSphereCluster"  
E0325 12:45:58.389969       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="unexpected error while probing vcenter for infrastructure.cluster.x-k8s.io/v1alpha3, Kind=VSphereCluster quentin-reproduce/quentin-reproduce: ServerFaultCode: Cannot complete login due to an incorrect user name or password." "controller"="vspherecluster" "name"="quentin-reproduce" "namespace"="quentin-reproduce"
I0325 12:45:58.410459       1 vspherecluster_controller.go:253] capv-controller-manager/vspherecluster-controller/quentin-reproduce/quentin-reproduce "msg"="Reconciling VSphereCluster"  
E0325 12:46:02.718540       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="unexpected error while probing vcenter for infrastructure.cluster.x-k8s.io/v1alpha3, Kind=VSphereCluster quentin-reproduce/quentin-reproduce: ServerFaultCode: Cannot complete login due to an incorrect user name or password." "controller"="vspherecluster" "name"="quentin-reproduce" "namespace"="quentin-reproduce"
I0325 12:46:02.758959       1 vspherecluster_controller.go:253] capv-controller-manager/vspherecluster-controller/quentin-reproduce/quentin-reproduce "msg"="Reconciling VSphereCluster"  
E0325 12:46:08.105904       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="unexpected error while probing vcenter for infrastructure.cluster.x-k8s.io/v1alpha3, Kind=VSphereCluster quentin-reproduce/quentin-reproduce: ServerFaultCode: Cannot complete login due to an incorrect user name or password." "controller"="vspherecluster" "name"="quentin-reproduce" "namespace"="quentin-reproduce"
I0325 12:46:08.186369       1 vspherecluster_controller.go:253] capv-controller-manager/vspherecluster-controller/quentin-reproduce/quentin-reproduce "msg"="Reconciling VSphereCluster"  
E0325 12:46:12.542381       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="unexpected error while probing vcenter for infrastructure.cluster.x-k8s.io/v1alpha3, Kind=VSphereCluster quentin-reproduce/quentin-reproduce: ServerFaultCode: Cannot complete login due to an incorrect user name or password." "controller"="vspherecluster" "name"="quentin-reproduce" "namespace"="quentin-reproduce"
I0325 12:46:12.703126       1 vspherecluster_controller.go:253] capv-controller-manager/vspherecluster-controller/quentin-reproduce/quentin-reproduce "msg"="Reconciling VSphereCluster"  
E0325 12:46:18.049232       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="unexpected error while probing vcenter for infrastructure.cluster.x-k8s.io/v1alpha3, Kind=VSphereCluster quentin-reproduce/quentin-reproduce: ServerFaultCode: Cannot complete login due to an incorrect user name or password." "controller"="vspherecluster" "name"="quentin-reproduce" "namespace"="quentin-reproduce"
I0325 12:46:18.369714       1 vspherecluster_controller.go:253] capv-controller-manager/vspherecluster-controller/quentin-reproduce/quentin-reproduce "msg"="Reconciling VSphereCluster"  
E0325 12:46:21.721239       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="unexpected error while probing vcenter for infrastructure.cluster.x-k8s.io/v1alpha3, Kind=VSphereCluster quentin-reproduce/quentin-reproduce: ServerFaultCode: Cannot complete login due to an incorrect user name or password." "controller"="vspherecluster" "name"="quentin-reproduce" "namespace"="quentin-reproduce"
I0325 12:46:22.361694       1 vspherecluster_controller.go:253] capv-controller-manager/vspherecluster-controller/quentin-reproduce/quentin-reproduce "msg"="Reconciling VSphereCluster"  
E0325 12:46:27.622971       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="unexpected error while probing vcenter for infrastructure.cluster.x-k8s.io/v1alpha3, Kind=VSphereCluster quentin-reproduce/quentin-reproduce: ServerFaultCode: Cannot complete login due to an incorrect user name or password." "controller"="vspherecluster" "name"="quentin-reproduce" "namespace"="quentin-reproduce"
I0325 12:46:28.903431       1 vspherecluster_controller.go:253] capv-controller-manager/vspherecluster-controller/quentin-reproduce/quentin-reproduce "msg"="Reconciling VSphereCluster"  
E0325 12:46:32.252579       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="unexpected error while probing vcenter for infrastructure.cluster.x-k8s.io/v1alpha3, Kind=VSphereCluster quentin-reproduce/quentin-reproduce: ServerFaultCode: Cannot complete login due to an incorrect user name or password." "controller"="vspherecluster" "name"="quentin-reproduce" "namespace"="quentin-reproduce"
I0325 12:46:34.812999       1 vspherecluster_controller.go:253] capv-controller-manager/vspherecluster-controller/quentin-reproduce/quentin-reproduce "msg"="Reconciling VSphereCluster"  
E0325 12:46:38.169252       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="unexpected error while probing vcenter for infrastructure.cluster.x-k8s.io/v1alpha3, Kind=VSphereCluster quentin-reproduce/quentin-reproduce: ServerFaultCode: Cannot complete login due to an incorrect user name or password." "controller"="vspherecluster" "name"="quentin-reproduce" "namespace"="quentin-reproduce"
I0325 12:46:43.289580       1 vspherecluster_controller.go:253] capv-controller-manager/vspherecluster-controller/quentin-reproduce/quentin-reproduce "msg"="Reconciling VSphereCluster"  
E0325 12:46:48.633480       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="unexpected error while probing vcenter for infrastructure.cluster.x-k8s.io/v1alpha3, Kind=VSphereCluster quentin-reproduce/quentin-reproduce: ServerFaultCode: Cannot complete login due to an incorrect user name or password." "controller"="vspherecluster" "name"="quentin-reproduce" "namespace"="quentin-reproduce"
I0325 12:46:58.873904       1 vspherecluster_controller.go:253] capv-controller-manager/vspherecluster-controller/quentin-reproduce/quentin-reproduce "msg"="Reconciling VSphereCluster"  
E0325 12:47:03.224677       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="unexpected error while probing vcenter for infrastructure.cluster.x-k8s.io/v1alpha3, Kind=VSphereCluster quentin-reproduce/quentin-reproduce: ServerFaultCode: Cannot complete login due to an incorrect user name or password." "controller"="vspherecluster" "name"="quentin-reproduce" "namespace"="quentin-reproduce"
I0325 12:47:10.826872       1 controller.go:281] controller-runtime/controller "msg"="Successfully Reconciled" "controller"="vspheremachine" "name"="quentin-reproduce-4vbmd" "namespace"="quentin-reproduce"
I0325 12:47:10.905846       1 controller.go:281] controller-runtime/controller "msg"="Successfully Reconciled" "controller"="vspheremachine" "name"="quentin-reproduce-8l2xn" "namespace"="quentin-reproduce"
I0325 12:47:11.006024       1 controller.go:281] controller-runtime/controller "msg"="Successfully Reconciled" "controller"="vspheremachine" "name"="quentin-reproduce-nk5tz" "namespace"="quentin-reproduce"
I0325 12:47:11.084940       1 vspheremachine_controller.go:321] capv-controller-manager/vspheremachine-controller/quentin-reproduce/quentin-reproduce-r5xgt "msg"="Waiting for bootstrap data to be available"  
I0325 12:47:11.085994       1 controller.go:281] controller-runtime/controller "msg"="Successfully Reconciled" "controller"="vspheremachine" "name"="quentin-reproduce-r5xgt" "namespace"="quentin-reproduce"
I0325 12:47:11.160512       1 controller.go:281] controller-runtime/controller "msg"="Successfully Reconciled" "controller"="vspheremachine" "name"="quentin-reproduce-tbp9c" "namespace"="quentin-reproduce"
I0325 12:47:11.242696       1 controller.go:281] controller-runtime/controller "msg"="Successfully Reconciled" "controller"="vspheremachine" "name"="quentin-reproduce-whtms" "namespace"="quentin-reproduce"
I0325 12:47:11.326170       1 controller.go:281] controller-runtime/controller "msg"="Successfully Reconciled" "controller"="vspheremachine" "name"="quentin-reproduce-xl6m7" "namespace"="quentin-reproduce"
```

We just need to understand why the generated docker image is 0.7.4-sha instead of 0.7.6

**Comment by QuentinBisson** [comment]
Do they even use this file?

**Comment by tfussell** [comment]
> Do they even use this file?

I'm fine with removing it for now.

**Comment by tfussell** [comment]
> We just need to understand why the generated docker image is 0.7.4-sha instead of 0.7.6

This is quite circuitous, but basically the version comes from `architect project version` which runs `cluster-api-provider-vsphere version` which is injected as ldflags generated with this script https://github.com/giantswarm/cluster-api-provider-vsphere/blob/master/hack/version.sh#L32 which uses `git describe --tags`. The issue is that the 0.7.6 tag is on the `release-0.7` branch, but I'm working on the `master` branch here. If we merge this to `master` and then cherry-pick to `release-0.7`, we should have the image like `0.7.6-<hash>` as expected.

**Review by QuentinBisson — APPROVED** [review]

**Pull request merged**
